In [1]:
#import numpy library
import numpy as np
import pandas as pd

### 1) Create Two numpy array of size 3 X 2 and 2 X 3

In [2]:
arr1 = np.empty([3,2],dtype = int)
arr2 = np.empty([2,3],dtype = int)
print("arr1 = ")
print(arr1)
print("arr2 = ")
print(arr2)

arr1 = 
[[242   0]
 [  0   0]
 [  0   0]]
arr2 = 
[[250   0   0]
 [  0   0   0]]


### 2) Randomly Initalize that array

In [3]:
arr1 = np.random.randint(10,size=np.shape(arr1))
arr2 = np.random.randint(10,size=np.shape(arr2))
print("arr1 = ")
print(arr1)
print("arr2 =")
print(arr2)

arr1 = 
[[6 8]
 [8 8]
 [0 5]]
arr2 =
[[3 9 6]
 [5 4 5]]


### 3) Perform matrix multiplication

In [4]:
mat_mul = np.matmul(arr1,arr2)
print("Matrix Multiplication = ")
print(mat_mul)

Matrix Multiplication = 
[[ 58  86  76]
 [ 64 104  88]
 [ 25  20  25]]


### 4) Perform elementwise matrix multiplication

In [5]:
ele_mat_arr1 = arr1*arr1
print(ele_mat_arr1)
ele_mat_arr2 = arr2*arr2
print(ele_mat_arr2)
ele_mat_mul = arr1*arr2.T
print(ele_mat_mul)

[[36 64]
 [64 64]
 [ 0 25]]
[[ 9 81 36]
 [25 16 25]]
[[18 40]
 [72 32]
 [ 0 25]]


### 5) Find mean of first matrix

In [6]:
first_mean = np.mean(arr1)
first_mean_by_cols = np.mean(arr1, axis=0)
first_mean_by_rows = np.mean(arr1, axis=1)
print(first_mean)
print(first_mean_by_cols)
print(first_mean_by_rows)

5.833333333333333
[4.66666667 7.        ]
[7.  8.  2.5]


### 6) Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version

In [7]:
df_mtcars = pd.read_csv("C:/Users/Admin/Desktop/Raj/Sem-7/ML-Materials/LAB1/mtcars.csv")
df_mtcars.head(5)

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [8]:
# for all columns
df_mtcars['mpg'] = df_mtcars['mpg'] - np.mean(df_mtcars['mpg'])
df_mtcars['cyl'] = df_mtcars['cyl'] - np.mean(df_mtcars['cyl'])
df_mtcars['disp'] = df_mtcars['disp'] - np.mean(df_mtcars['disp'])
df_mtcars['hp'] = df_mtcars['hp'] - np.mean(df_mtcars['hp'])
df_mtcars['drat'] = df_mtcars['drat'] - np.mean(df_mtcars['drat'])
df_mtcars['wt'] = df_mtcars['wt'] - np.mean(df_mtcars['wt'])
df_mtcars['qsec'] = df_mtcars['qsec'] - np.mean(df_mtcars['qsec'])
df_mtcars['vs'] = df_mtcars['vs'] - np.mean(df_mtcars['vs'])
df_mtcars['am'] = df_mtcars['am'] - np.mean(df_mtcars['am'])
df_mtcars['gear'] = df_mtcars['gear'] - np.mean(df_mtcars['gear'])
df_mtcars['carb'] = df_mtcars['carb'] - np.mean(df_mtcars['carb'])

In [9]:
#After converted to MCV
df_mtcars.head(5)

model       mpg     cyl        disp       hp      drat  \
0          Mazda RX4  0.909375 -0.1875  -70.721875 -36.6875  0.303437   
1      Mazda RX4 Wag  0.909375 -0.1875  -70.721875 -36.6875  0.303437   
2         Datsun 710  2.709375 -2.1875 -122.721875 -53.6875  0.253437   
3     Hornet 4 Drive  1.309375 -0.1875   27.278125 -36.6875 -0.516563   
4  Hornet Sportabout -1.390625  1.8125  129.278125  28.3125 -0.446563   

        wt     qsec      vs       am    gear    carb  
0 -0.59725 -1.38875 -0.4375  0.59375  0.3125  1.1875  
1 -0.34225 -0.82875 -0.4375  0.59375  0.3125  1.1875  
2 -0.89725  0.76125  0.5625  0.59375  0.3125 -1.8125  
3 -0.00225  1.59125  0.5625 -0.40625 -0.6875 -1.8125  
4  0.22275 -0.82875 -0.4375 -0.40625 -0.6875 -0.8125